### ISSUE TITLE
An open source community activity analysis project

### ISSUE THREAD

**Issue by ycp8023** [chaoss/wg-metrics-development#182]
# Metric basics

* **Metric title**: wuly-metric
* **Metric summary** (1-2 sentences):
The Activity of open source community was investigated from four aspects: Project Velocity, New Comer, Response Time and Social Activity, and an evaluation score was synthesized by combining these four scores. The scores are graded into four grades: S, A, B and C
* **Why should this metric be created?** (1-2 sentences):
We have the course of Introduction to Open Source software development and this project is our homework.The project will eventually complete more than five (nine so far) open source community activity analyses of more than 100 stars. The collected open source community data is analyzed according to feasible activity evaluation indicators, and the results are visually displayed. All the data collected and frontend demo is displayed here ：https://gitee.com/unique021203/openSource.git

# Data collection and measurement

**Are there existing tools that could collect this data?** If yes, list them:
<html>
<body>
<p style="box-sizing: border-box; margin: 0px 0em 16px; line-height: 1.6; word-break: break-word; color: rgb(64, 72, 91); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Liberation Sans&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Wenquanyi Micro Hei&quot;, &quot;WenQuanYi Zen Hei&quot;, &quot;ST Heiti&quot;, SimHei, SimSun, &quot;WenQuanYi Zen Hei Sharp&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">The nine repos selected for analysis in this project are as follows:</p>

name | repo
-- | --
rails | https://github.com/rails/rails
DBeaver | https://github.com/dbeaver/dbeaver
EasyPhotos | https://github.com/HuanTanSheng/EasyPhotos
PaddleOCR | https://github.com/PaddlePaddle/PaddleOCR
PyQt5 | https://github.com/PyQt5/PyQt
LeetCode | https://github.com/doocs/leetcode
Wechat-ChatGPT | https://github.com/fuergaosi233/wechat-chatgpt
Matisse | https://github.com/zhihu/Matisse
OpenFace | https://github.com/TadasBaltrusaitis/OpenFace

</body>
</html>
GitHub provides an api interface that directly returns json for data collection.The collected data includes commits, PRs, issues, comments of each warehouse, etc. For details, see README in the Data section. At present, the data volume has reached more than 100,000.

**If this metric involves a lot of raw data, what filters would you use to narrow down the metric?** If applicable, describe ways to filter the data into smaller segments:

**How would you visualize this metric?** If you have an idea on how this metric should be visualized or displayed so it makes the most sense to a viewer, describe that here:
For the data collected, the project team uses echarts for data visualization. We made statistics on the data of each warehouse by month, visualized it, and analyzed its dynamic changes, including the monthly increase of commit, issue, PR, comment, etc. At the same time, we counted the average resolution time of each warehouse issue, the average resolution time of pr, etc., and analyzed the activity from the perspective of dynamic data.Finally, we rated the performance of each warehouse in four aspects: Project Velocity, New Comer, Response Time and Social Activity, and gave a total rating.

![image](https://user-images.githubusercontent.com/79349653/207253908-e0ebb069-4e38-45e2-b1fb-656addf2dbc5.png)

# About you

* **Are you interested in authoring this metric together with the Working Group?**: yes
* **Have you attended a CHAOSS Working Group meeting before?**: no
* **If not, would you consider joining one to discuss your metric idea?**: yes
* **Anything else you would like us to know?**:

**Comment by eyehwan** [comment]
I am thinking this is a metrics model instead of a metric. : )
@ycp8023 do you mind that if I refer your issue to https://github.com/chaoss/wg-metrics-models?  :)
You can also discuss with us about your idea through CHAOSS slack #wg-metrics-model channel.

**Comment by ElizabethN** [comment]
I'm going to close this for now, as it seems to have been resolved via the Community Activity metrics model.
