### ISSUE TITLE
New Metric: Change Request Closure Ratio

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/wg-metrics-development#187]
This issue is created to collect comments on the Change Request Closure metric. Note: This was renamed from "Keeping up with Change Requests"

This metric can be found here: [Google Doc](https://docs.google.com/document/d/1Sa40vxK8AXfXS8m4zhG2Wr6vbpZydv6Rz00O-2WMFXk/edit?usp=sharing)

## CHAOSS Metric Quality Checklist
This checklist is used for new metrics to ensure we follow CHAOSS quality standards and processes. 

### Process

- [ ] Add the new metric to release notes issue in working group repo
- [ ] Update the [Metrics Spreadsheet](https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit) to indicate that the metric is under community review.

**When above steps are completed:**

### Content Quality

- [x] Required headings are filled in
- [x] If any, ensure links to other CHAOSS metrics work
- [x] Optional headings that have no content are removed
- [x] Contributors section lists those contributors that want to be named
- [x] The name of the metric is the same in all locations

### Technical Requirements

- Message that the metric will be part of the next regular release is at top of page: 

### This metric is a release candidate. To comment on this metric please see Issue [#[put the respective Issue Number here]](URL to issue). Following a comment period, this metric will be included in the next regular release.

- Metric file name is the full metric name and only contains lower case letters and hyphens (“-”) for spaces
- Images are included using markdown and absolute links (as described in the metrics template)
- Images have at least one empty line above and below them
- Ensure images are placed in image folder and followed [naming convention](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md)
- Ensure tables within metric are converted as images and placed in the image folder (both original MD and screenshotted PNG format) and follow the naming convention
- No HTML code in the metrics markdown.

**Comment by eyehwan** [comment]
Seeing that you are still typing on the doc, so I will take a look tomorrow. :)

**Comment by geekygirldawn** [comment]
@germonprez Can we add this to the Common WG agenda for discussion today? I'm still working on it now, but should have something ready to discuss by the meeting time :)

@eyehwan - thanks! It should be ready for you to review by your morning tomorrow.

**Comment by germonprez** [comment]
Certainly! I'll make sure it is on the agenda.

**Comment by geekygirldawn** [comment]
@germonprez @ElizabethN @klumb - thanks for all of your feedback today. I've reworked this to be a ratio metric and would love to have you do another pass at it with more feedback!

@eyehwan I'd appreciate your feedback, too!

**Comment by geekygirldawn** [comment]
I've moved the metric from the gdoc to PR #188

**Comment by ElizabethN** [comment]
Closing this as it seems to have been resolved.
