### ISSUE TITLE
Release Candidate Comments (New Contributors Closing Issues)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-metrics-development#190]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about New Contributors Closing Issues**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/New_Contributor_Closing_Issues.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by ElizabethN** [comment]
Doing a little repo cleanup today and I'm going to close this, as we are currently updating all metrics to a new metric template, including a refresh.
