### ISSUE TITLE
New Contributors Metrics Release Candidate

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-metrics-development#191]
This issue was created to collect comments about the rolling release of "New Contributors"

This thread is for comments about New Contributors

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/New_Contributors.md

**Comment by ElizabethN** [comment]
Doing a little repo cleanup today and I'm going to close this, as we are currently updating all metrics to a new metric template, including a refresh.
