### ISSUE TITLE
Inactive Contributors : Metric Release Candidate

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-metrics-development#192]
This issue was created to collect comments about the rolling release of "Inactive Contributors"

This thread is for comments about the proposed metric **Inactive Contributors**

The proposed new metric is here: https://github.com/chaoss/wg-evolution/blob/master/metrics/Inactive_Contributers.md

The Comment period start date is May 6, 2020, and will conclude on June 6, 2020.

**Comment by ElizabethN** [comment]
Doing a little repo cleanup today and I'm going to close this, as we are currently updating all metrics to a new metric template, including a refresh.
