### ISSUE TITLE
Release/Revision Change_Requests_Declined.md

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-metrics-development#194]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Change_Requests_Declined.md

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Change_Requests_Declined.md

See all release candidates at: https://chaoss.community/metrics/

**Comment by ElizabethN** [comment]
Doing a little repo cleanup today and I'm going to close this, as we are updating all metrics to the new template and doing a refresh of them all in the process.
