### ISSUE TITLE
New Metric: Time Waiting for a Submitter Action

### ISSUE THREAD

**Issue by dicortazar** [chaoss/wg-metrics-development#87]
This ticket comes from a broader discussion related to [responsiveness metrics](https://github.com/chaoss/wg-common/issues/13). 

This ticket aims at discussing the **Time to Waiting for a Submitter Action** metric.

Google doc is available at https://docs.google.com/document/d/11IHoWZYO4aWg638J15hOX7u8hAfRvi6nhF7dTzsy0fo/edit?usp=sharing

**Comment by vinodkahuja** [comment]
We are currently working on this and the discussion is happening in the google doc.

**Comment by dicortazar** [comment]
We worked on the doc for a while. It is almost fully filled. Now we should go for the sanity check.
